#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Stopwatch.Droid.Resource", IsApplication=true)]

namespace Stopwatch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_state_list_animator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int minus_to_plus = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int plus_to_minus = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int rotate_anticlockwise = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int rotate_clockwise = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int dark_grey = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int light_grey = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int sa_green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int sa_green_dark = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sa_green_transparent = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fab_elevation = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fab_rise = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int animated_minus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animated_plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fab_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int minus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pause = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int play = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int reload = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int StartButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int StartButton_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int StartButton_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int stop = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0003
			public const int fab = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int fab_container = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int fab_pause = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int fab_reload = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int fab_stop = 2131361794;
			
			// aapt resource value: 0x7f0a0006
			public const int input_login = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int input_password = 2131361799;
			
			// aapt resource value: 0x7f0a0005
			public const int scrollView1 = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public const int start_button = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int start_layout = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int submit_button = 2131361800;
			
			// aapt resource value: 0x7f0a000c
			public const int textClock = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int user_name = 2131361802;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Stopwatch = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int FloatingActionButton = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int FloatingActionButton_Mini = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int StartButton = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
