#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Stopwatch.Droid.Resource", IsApplication=true)]

namespace Stopwatch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_state_list_animator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int minus_to_plus = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int plus_to_minus = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int rotate_anticlockwise = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int rotate_clockwise = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int dark_grey = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int light_grey = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int sa_green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int sa_green_dark = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int sa_green_transparent = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fab_elevation = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fab_rise = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int margin_medium = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int margin_small = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int okButton_height = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int okButton_width = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int padding_small = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int textSize_clock = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int textSize_userName = 2131099657;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int animated_minus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animated_plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fab_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int minus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pause = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int play = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int reload = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int StartButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int StartButton_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int StartButton_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int stop = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int fab = 2131427333;
			
			// aapt resource value: 0x7f0b0002
			public const int fab_container = 2131427330;
			
			// aapt resource value: 0x7f0b0006
			public const int fab_pause = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int fab_reload = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int fab_stop = 2131427332;
			
			// aapt resource value: 0x7f0b0008
			public const int input_login = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int input_password = 2131427337;
			
			// aapt resource value: 0x7f0b0001
			public const int main_content = 2131427329;
			
			// aapt resource value: 0x7f0b0010
			public const int menu_about = 2131427344;
			
			// aapt resource value: 0x7f0b000f
			public const int menu_zero = 2131427343;
			
			// aapt resource value: 0x7f0b0007
			public const int scrollView1 = 2131427335;
			
			// aapt resource value: 0x7f0b000d
			public const int start_button = 2131427341;
			
			// aapt resource value: 0x7f0b000b
			public const int start_layout = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int submit_button = 2131427338;
			
			// aapt resource value: 0x7f0b000e
			public const int textClock = 2131427342;
			
			// aapt resource value: 0x7f0b0000
			public const int toolbar = 2131427328;
			
			// aapt resource value: 0x7f0b000c
			public const int user_name = 2131427340;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int fab_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Stopwatch = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Toolbar = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int stopwatchMenu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Email = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int LoginError = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int Password = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int FloatingActionButton = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int FloatingActionButton_Mini = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int StartButton = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
